
name: Convert Markdown to HTML and Deploy

on:
  push:
    branches:
      - master  # Déclencher ce workflow sur des commits sur la branche principale (master)
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert Markdown to HTML
      run: |
        mkdir -p output
        for file in $(find . -name '*.md'); do
          pandoc "$file" -o "output/$(basename "${file%.*}.html")"
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        publish_branch: gh-pages
